#define MAKE_STRING(STR) #STR,
#define MAKE_ENUM(X) X,
#define FOREACH_ROLE(ROLE) \
    ROLE(RoleA) \
    ROLE(RoleB) \

#define MAKE_ENUM_STR(NAME, ENUM_GENERATOR) \
    char *NAME[] = { ENUM_GENERATOR(MAKE_STRING) };

#define MAKE_ENUM_ENUM(NAME, ENUM_GENERATOR) \
    enum NAME { ENUM_GENERATOR(MAKE_ENUM) };

#define MAKE_ENUM_STR_ENUM(NAME_PREFIX, ENUM_GENERATOR) \
    MAKE_ENUM_STR(NAME_PREFIX##Names, ENUM_GENERATOR)\
    MAKE_ENUM_ENUM(NAME_PREFIX, ENUM_GENERATOR)\

MAKE_ENUM_STR_ENUM(Roles, FOREACH_ROLE)

#define x(y) y##aa##y
x(9)

char *c = MAKE_STRING(RoleA);

char *s[] = {
    FOREACH_ROLE(MAKE_STRING)
};

enum Roles {
    FOREACH_ROLE(MAKE_ENUM)
};

MAKE_ENUM_STR(s2, FOREACH_ROLE)
MAKE_ENUM_ENUM(es2, FOREACH_ROLE)
