test:
	cc $@.c -o /tmp/$@ && /tmp/$@

maxtime:
	cc maxtime.c -o /tmp/maxtime && /tmp/maxtime

words:
	cc words.c -o /tmp/word && echo "abc def geh a a b cd cd ea zz 4444 4444 123123" | /tmp/word

reverse:
	cc reverse.c -o /tmp/reverse && echo "abc def geh\n a a b cd cd ea zz 4444 4444 123123" | /tmp/reverse
